# Generated by Django 2.2.6 on 2019-10-19 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_remove_ticketoffering_game'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketOffering',
        ),
    ]
