# Generated by Django 2.2.6 on 2019-10-19 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_ticketoffering'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='datetime',
            new_name='game_dt',
        ),
    ]
