# Generated by Django 2.2.6 on 2019-10-19 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_auto_20191019_1115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketOffering',
        ),
    ]
