# Generated by Django 2.2.6 on 2019-10-19 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0007_ticketoffering'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketOffering',
        ),
    ]
