# Generated by Django 2.2.6 on 2019-10-19 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0010_auto_20191019_1220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketOffering',
        ),
    ]
