# Generated by Django 2.2.6 on 2019-10-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0012_ticketoffering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketoffering',
            name='location',
            field=models.CharField(choices=[('Hill', 'Hill'), ('Upper', 'Upper Deck'), ('Lower', 'Lower Deck')], max_length=6),
        ),
    ]
