# Generated by Django 2.2.6 on 2019-10-20 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0013_auto_20191019_1329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketoffering',
            options={'ordering': ['price']},
        ),
    ]
