# Generated by Django 2.2.6 on 2019-10-22 18:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0015_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketoffering',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
